---
title: "Conclusion of biomimicry"
---

Biomimicry allows you to optimize certain objects, making them more efficient!
As in tapestry where the bottom of the rivers offers unrepeated patterns, the coat of the polar bear which offers a heat resistant fabric, the beak of the kingfisher allows to optimize the transport.

There is not only optimization, there is also the discovery of new materials! As in medicine thanks to jellyfish with their collagen or to mussels with their adhesion products ... We have new medical products.
Robotics is also progressing enormously thanks to nature. Scientists innovate in "soft" robotics Inspired by the remora or the structure of the eye.
In short, these articles show us that biomimicry is essential, in development and in solutions for our future.
It was biomimicry that made me want to do biology, so I really liked making this portfolio even if sometimes the subjects were complex, I found them fascinating! I love nature for its beauty and its complexity. I always love to know more about our world

Here is what biomimicry is ... Is it normal that it is unknown to the general public? When will all this biodiversity (all this knowledge) be finally respected at its fair value?
