---
title: "My english activity log"
---

Biomimicry is a really exciting subject! These few articles will discover this extraordinary science.
English is a language used by all. It is therefore very important to master it.

I try to use English more and more, in order to improve myself.
The first use is for series. I'm a fan of 2 or 3 series and I cannot wait for the French version. English is the international language it is in this language that episodes were released first.
Then I use English to expand my knowledge. When I look for information, they are always more complete in English. If I want an answer it's in English that I would have the most complete and relevant.
English also serves me in the communication of idea, if I want to give or receive advice with someone who does not speak French, I would have more chance to have an answer and to be understood by speaking English which is the international language.
I play video games from time to time and English is valuable to me.
My level of English is not perfect and I know I have trouble speaking. That's why I attend at classes on Saturdays that will improve my oral in English. I hope these courses will help me to express myself better.

09/28/2019: English lessons on Saturday: Beginning of classes on Saturday, I was placed in level A2. We review the times of the simple present. And we introduce ourselves.

10/05/2019: English lessons on Saturday : New course, we learned to use the propositions. we also saw the present continues and the numbers. We had oral conversations about holiday.

10/12/2019: English lessons on Saturday: We have seen the habits. Orally, we trained to book a trip with different activities

10/19/2019: English lessons on Saturday: We made comparison exercises between the present continuous and simple. We also did oral exercises on what we liked and what we didn't like.

10/26/2019: English lessons on Saturday: Orally, we have planned meetings and invitations. We also listened to convents

11/02/2019: English lessons on Saturday: We have seen today the nuances and variations of sentences

11/04/2019: I saw a mini-film by Loic Nottet, the film is called Candy Land. It's awesome. This man is an accomplished artist! He masters, singing, dancing, writing, ... He is also a little mad

11/16/2019: English lessons on Saturday :Orally, we continued to learn to plan an appointment

11/23/2019: English lessons on Saturday : We learned to speak in the future. We read a text on future projects. We also saw the verb modal

11/30/2019: English lessons on Saturday: We reviewed the prepositions, we also saw the difference between "going to" and "will". We also had to speak orally about the idea that we were shaping the future.

12/07/2019: English lessons on Saturday: In the course, we learned the probabilities.

12/14/2019: English lessons on Saturday : We saw the simple past. We talked about the elements that we have done in the past.

01/11/2020: English lessons on Saturday: We talked about what we did during our "holiday"

01/18/2020: English lessons on Saturday: We saw the irregular verbs and we had to speak orally about what we observed on images.

01/25/2020: English lessons on Saturday: we have to explain how our weeks are going. We learned the variations of sentences after learning a new.

02/01/2020: English lessons on Saturday: We had a text with criminal potential. We had to read his alibi and see if he matched the tickets.

02/15/2020: English lessons on Saturday: We learned to describe photos in more detail, we also learned the difference between "how many" and "how much."

02/22/2020: English lessons on Saturday: We had 8 photos and we created a whole story behind

02/29/2020: English lessons on Saturday: We learned who, which, ... and we continued the photos to describe

03/07/2020: English lessons on Saturday: We have finished describing the photos





