---
title: "Introduction to biomimicry"
---

The theme of this portfolio is "Biomimicry". I chose this theme because it is something that fascinates me and I think it is the way to combine nature and technology. Unfortunately, many people do not know this science and its place in society. And they don't realize how important it will be for the future! I want to tackle this subject which fascinates me so much and which is essential for me!
The first question is what is biomimicry?
It is a science inspired by nature to innovate sustainably. We can draw inspiration from nature at the level of these processes, forms or functions of the living. The objective is to create new technologies through nature!
Biomimicry everywhere! In medicine, architecture, technology, but also every day!
Another question that could be asked: what does biomimicry bring us?
Biomimicry is today the solution to a major problem, namely the huge conflict between economy and ecology. Biomimicry can link the two, it allows us to develop economically while respecting the environment. With biomimicry, we are developing new technologies, but since they come from nature, these technologies are not in conflict with ecology! Biomimicry has other advantages.
First, biomimicry can lead to a waste-free world. Since we are inspired by nature, production can be in cycle and not in a straight line.
Second, biomimicry makes us understand how precious and important resources are. Nature is a library. Each species is a book with a lot of knowledge to bring to humans.
Humanity uses resources and species as material goods, when they are much more than that. We can't breathe water like a fish, we can't fly through the air like a bird ...
Third, humanity is moving away from nature, we consider animals to be different from us while we are also animals. Many people today take plants and animals as parasites. Biomimicry allows you to refocus.
In short, here are nine scientific articles that talk about biomimicry. In these articles, there are concrete examples, other theories but always with immense possibilities!
Many sectors are affected. The structure of nature helps in architecture, the components of nature help in medicine, the texture helps in textiles and the function helps in engineering. Nature has millions of years of progress on man. With these millions of years, she has managed to experiment and classify the best of these creations!


